TailsKitsune/Eiyuden-Chronicles_Retranslated

text_DeepL/MainScenario_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3169161912324659817.txt

My edits of the first half of Main Scenario 01.
I made it to line [421]. This gets you to just after the golem fight, after the meeting between Dux and the other Lords and Rulers.
You'll see some edits to lines [714] and after, because there is a dialogue branch that puts the player here for a bit before it doubles back.
I'll try to hammer out the other half of Main Scenario 01 next week.

Update MainScenario_01_en-CAB First Half Edit Pass

---

text_DeepL/MainScenario_02_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5619663750649154153.txt

Tags added based on version MainScenario_02_ja-CAB.txt:
- strength
- autosubmit

Update MainScenario_02_en-CAB: Tags Added

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

Tags added based on version MainScenario_03_ja-CAB.txt:
- strength
- autosubmit
The following codes "SInt64 m_Id = 4227125268", "SInt64 m_Id = 4235513885" were not modified. I am not sure how to add the Tag: ruby.

Update MainScenario_03_en-CAB: Tags Added

---

text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt

Tags added based on version MainScenario_04_ja-CAB.txt:
- strength
- autosubmit
The following code "SInt64 m_Id = 4411674657" was not modified. I am not sure how to add the Tag: ruby.

Update MainScenario_04_en-CAB: Tags Added

---

text_DeepL/MainScenario_05_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6787315574313703913.txt

Tags added based on version MainScenario_05_ja-CAB.txt:
- strength
- autosubmit
The following code "SInt64 m_Id = 2838810652" was not modified. I am not sure how to add the Tag: ruby.

Update MainScenario_05_en-CAB: Tags Added

---

text_DeepL/MainScenario_06_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--4856358632507853926.txt

Tags added based on version MainScenario_06_ja-CAB.txt:
- strength
- autosubmit
The following code "SInt64 m_Id = 4130656260" was not modified. I am not sure how to add the Tag: ruby.

Update MainScenario_06_en-CAB: Tags Added

---

text_DeepL/MainScenario_07_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1657815873690128415.txt

Tags added based on version MainScenario_07_ja-CAB.txt:
- strength
The following codes:
- SInt64 m_Id = 3044331543
- SInt64 m_Id = 3052720159
- SInt64 m_Id = 3052720164
- SInt64 m_Id = 3052720165
- SInt64 m_Id = 3056914432
- SInt64 m_Id = 3073691668
- SInt64 m_Id = 3077885954
- SInt64 m_Id = 3098857514 
were not modified. I am not sure how to add the Tag: ruby.

Update MainScenario_07_en-CAB: Tags Added

---

text_DeepL/MainScenario_08_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-384372531782332358.txt

Tags added based on version MainScenario_08_ja-CAB.txt:
- strength
- autosubmit
The following codes:
- SInt64 m_Id = 3212103710
- SInt64 m_Id = 3233075224
- SInt64 m_Id = 3233075225
- SInt64 m_Id = 3258241046
- SInt64 m_Id = 3266629635
- SInt64 m_Id = 3270823938
- SInt64 m_Id = 3279212552
- SInt64 m_Id = 3300184086 
were not modified. I am not sure how to add the Tag: ruby.
Special Case:
- SInt64 m_Id = 3279212559 (Added: shake duration, strength. Omitted: ruby)

Update MainScenario_08_en-CAB: Tags Added

---

text_DeepL/MainScenario_09_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1231159473249864508.txt

Tags added based on version MainScenario_09_ja-CAB.txt:
- strength
- autosubmit
The following codes:
- SInt64 m_Id = 3061108755
- SInt64 m_Id = 3077885987
- SInt64 m_Id = 3082080265
- SInt64 m_Id = 3082080282
- SInt64 m_Id = 3082080288
- SInt64 m_Id = 3098857505
- SInt64 m_Id = 3111440391
- SInt64 m_Id = 3124023306
- SInt64 m_Id = 3153383424
- SInt64 m_Id = 3153383425
- SInt64 m_Id = 3195326471
were not modified. I am not sure how to add the Tag: ruby.
Special Cases:
- SInt64 m_Id = 3144994851 (Added: shake duration, strength. Omitted: ruby)
- SInt64 m_Id = 33459904211324928 (Added: shake duration, strength, autosubmit. Omitted: ruby)

Update MainScenario_09_en-CAB: Tags Added

---

text_DeepL/AccessoryShopTalkText_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7497517779182209910.txt

Out-of-game edit for AccessoryShopTalk to learn editing and how to github.
Might revisit this once I meet the shopkeeper and have more context to his lines.

Update AccessoryShopTalkText_en-CAB Edits

---

text_DeepL/MainScenario_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3169161912324659817.txt

Reverted "Lycan" to "Beastman" in line [82], as discussed.
Progressed Edit (First Pass) from [421] to [486].
The Main Scenario requires us to spread out and perform recruitment scenarios at this point, so progress is stalled until I can complete those and loop back into the quest line.
There is a \<CHECK LINE> tag I left for line [477] that I couldn't quite understand. Its Sabine commenting on the MC's face.
To me, Sabine read like she was saying that Nowa was in a "dangerous situation", but a friend who knows Japanese told me that she was actually saying that Nowa has a "nervous look".
Hope the 2nd pass can make better sense of that line.

Update MainScenario_01_en-CAB Edited (1st Pass) [421] to [486]

---

text_DeepL/Main_Battle_Gimmick_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1701475196546212094.txt

Lines [83] - [96] is Mellore's Gopher Boss Battle.
I only edited line [83] - [91], because the lines after that in Mellore's boss battle don't have text boxes, and thus aren't displayed.
If you want me to, I can go and edit the hidden lines for Mellore's boss battle just for completion's sake.

Update Main_Battle_Gimmick_01 Mellore's Gopher Boss Battle

---

text_DeepL/MainScenario_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3169161912324659817.txt
text_DeepL/Scenario_ch_00110_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5722627356705386946.txt
text_DeepL/Scenario_ch_00480_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4305415292022829091.txt
text_DeepL/Scenario_ch_00610_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-1403403604931782588.txt
text_DeepL/Scenario_ch_00750_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3477371704773160866.txt

Just minor edits and fixes to the work I'd submitted before.
This is NOT progression nor is it a 2nd pass.

Minor Edits to MS 01, Scenario 00110, 00480, 00610, 00750

---

text_DeepL/HeroTalk_ch_00120_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4158445592358523206

DeepL translation of Hero_Talk_00120

HeroTalk_ch_00120_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4158445592358523206

---

text_DeepL/HeroTalk_ch_00150_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--8774124211816196165

DeepL translation of Hero_Talk_00150

HeroTalk_ch_00150_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--8774124211816196165.txt

---

text_DeepL/HeroTalk_ch_00160_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1765468253659387797.txt
text_DeepL/HeroTalk_ch_00170_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-1952789634586449719.txt
text_DeepL/HeroTalk_ch_00180_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6498813262457487165.txt
text_DeepL/HeroTalk_ch_00190_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-8573574797052688986.txt

DeepL translation of Herotalk 00160, Herotalk 00170, Herotalk 00180, Herotalk 00190. Fixed parsing issues on multiple.

Herotalk 00160 and Herotalk 00170  DeepL

---

text_DeepL/MainScenario_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3169161912324659817.txt

Progressed from line [484] to [598]. Stopped just before entering the Mine Shaft after General Kogen.
Herotalk 00220 - Yusuke - Line [0] - Gets called after MainScenario_01 Line [543]
Herotalk 00750 - Francesca - Line [2] - Gets called after MainScenario Line [576]
Herotalk 00610 - Iugo - Line [3] - Gets called after MainScenario Line [591]
I'm starting to think that the called lines for HeroTalk are either random, or there's somekind of order of operations to them. Each example of a called HeroTalk line today replaced one of Lian's lines in the script.
The overall message was the same, its just one of the other characters saying it.

Update MainScenario_01_en Progressed Edit (First Pass) from [484] to [596]

---

text_DeepL/HeroTalk_ch_00200_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7193732988291029225.txt
text_DeepL/HeroTalk_ch_00210_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7738187429070814170.txt

DeepL translate Herotalk 00200 and 00210

DeepL translate Herotalk 00200 and 00210

---

text_DeepL/Main_Battle_Gimmick_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1701475196546212094.txt

Line [0] to [33] is Kogen boss battle.
Line [34] to [55] is Mine Shaft chasing after Kogen. Above lines edited.
Will go back to edit the Golem boss fight lines in the future.

Update Main_Battle_Gimmick_01_en Kogen Boss Fight and Mineshaft (Contains 2nd Update)

---

text_DeepL/Scenario_ch_00900_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--4004182557547618371.txt

TL'd with DeepL and edited. Hiro is only fully recruitable later but I think I have a decent read on him.
His EN TL lines are mostly accurate with minimal liberties taken, but I've given him our AI TL treatment for the sake of completion.

Scenario 00900 - Hiro - Recruitment - TL'd, Edited, Uploaded

---

text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt
text_DeepL/HeroTalk_ch_00230_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2889277966476298600.txt

DeepL of Herotalk 00220 and 00230

DeepL of Herotalk 00220 and 00230

---

text_DeepL/HeroTalk_ch_00240_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4432029035299212649.txt
text_DeepL/HeroTalk_ch_00250_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-884902848403040935.txt
text_DeepL/HeroTalk_ch_00260_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--551910541855418105.txt
text_DeepL/HeroTalk_ch_00270_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--8316158749326420191.txt
text_DeepL/HeroTalk_ch_00280_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6332373151164668700.txt
text_DeepL/HeroTalk_ch_00290_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--4118667326065700286.txt
text_DeepL/HeroTalk_ch_00300_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7949039865492490196.txt
text_DeepL/HeroTalk_ch_00310_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2642830767903144476.txt
text_DeepL/HeroTalk_ch_00320_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5096675320149023608.txt
text_DeepL/HeroTalk_ch_00330_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6909955746722633120.txt
text_DeepL/HeroTalk_ch_00340_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2220835408850628315.txt
text_DeepL/HeroTalk_ch_00350_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4830932581905731820.txt
text_DeepL/HeroTalk_ch_00370_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--9142000436487038974.txt
text_DeepL/HeroTalk_ch_00380_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7258667563930476794.txt
text_DeepL/HeroTalk_ch_00390_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-518523706721970105.txt
text_DeepL/HeroTalk_ch_00400_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6925983728841025420.txt
text_DeepL/HeroTalk_ch_00410_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-8714827694142450807.txt
text_DeepL/HeroTalk_ch_00420_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6660668013819770382.txt
text_DeepL/HeroTalk_ch_00430_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6011090276019231049.txt
text_DeepL/HeroTalk_ch_00440_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--4459370524813146008.txt
text_DeepL/HeroTalk_ch_00460_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7252531523354282815.txt
text_DeepL/HeroTalk_ch_00470_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-724342051935432873.txt
text_DeepL/HeroTalk_ch_00480_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7981833044287538288.txt
text_DeepL/HeroTalk_ch_00530_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--165380487124544502.txt
text_DeepL/HeroTalk_ch_00540_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--923702435831749607.txt
text_DeepL/HeroTalk_ch_00550_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-656408962592219255.txt
text_DeepL/HeroTalk_ch_00570_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5044796288900024632.txt
text_DeepL/HeroTalk_ch_00580_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6073765549828348531.txt
text_DeepL/HeroTalk_ch_00581_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7210781601577883519.txt

Hero talks  00240, 00250, 00260, 00270, 00280, 00290, 00300, 00310, 00320, 00330, 00340, 00350,  00370, 00380, 00390, 00400, 0041, 00420, 00430, 00440, 00460, 00470, 00480, 00530, 00540, 00550, 00570, 00580, and .00581

Hero talks  00240 - 00581

---

text_DeepL/MainScenario_02_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5619663750649154153.txt

Progressed line [20] to [281].
I also replaced all instances of "Noah" with "Nowa", so all edits beyond line [281] are just that for now.

Update MainScenario_02_en Edit Lines [20] to [281]

---

text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt

Progressed edit (first pass) from line [10] to [26].

Update HeroTalk_ch_00110_en Edited line [10] to [26]

---

text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt

Update HeroTalk_ch_00220_en Edited line [10] to [26]

---

text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt

Transferred my stored edits.
Lines [0] to [26] have been edited (first pass).

Update HeroTalk_ch_00610_en, Line [0] - [38] Edited (first pass)

---

text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt

Transferred my stored edits.
Lines [0] to [26] have been edited (first pass).

Update HeroTalk_ch_00750_en, Line [0] - [38] Edited (First Pass)

---

text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt

Progress from line [27] to [33]

Update HeroTalk_ch_00110_en - Line [27] to [38] - Edit Progression

---

text_DeepL/Duel_Scenario_2_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-4981793771394093956.txt

Only contains the first Duel of the game, between Nowa and Seign

Duel_Scenario_2_en TL'd and Edited (First Pass)

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt
text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt
text_DeepL/MainScenario_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3169161912324659817.txt

Some minor fixes to MS01.
1 change to a previously edited line in Herotalk 00110 Mellore.
Repurposed and uploaded Herotalk 00010 to function as contextual devnotes for future Herotalk work. Will be updating this overtime.

Minor Grammar Fixes, Edits, and Uploaded Context file

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

Progressed main story from lines [61] to [176].
Includes lines [447] to [469], alternate dialogue branches.

Update MainScenario_03 - Edit Progression

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt

Progressed context notes from Line [39] to [41].

Update HeroTalk_ch_00010 - Line [39] to [41]

---

text_DeepL/Scenario_ch_00330_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2372740589275057262.txt
text_DeepL/Scenario_ch_01130_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6382554582248604650.txt

Recruitment scenarios for 00330 (Ormond) and 01130 (Galdolf), DeepL TL'd and edited.

Scenarios 00330 & 01130 - Ormond & Galdolf - Upload

---

text_DeepL/HeroTalk_ch_00940_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--134124956078721526.txt

This is Martha.
Edited all of her old lines up to line [45].

Update HeroTalk_ch_00940_en Edits Started

---

text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt

Progressed from line [42] to [45]

Update HeroTalk_ch_00750_en Edit Progression

---

text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt

Progressed from line [42] to [45]
Minor change to Iugo's joke insert line in his own recruitment quest.

Update HeroTalk_ch_00610_en Edit Progression

---

text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt

Progressed from line [42] to [45]

Update HeroTalk_ch_00220_en Edit Progression

---

text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt

Progressed from line [42] to [45]

Update HeroTalk_ch_00110_en Edit Progression

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

Progressed edit from [177] to [219].

Update MainScenario_03_en Edit Progression

---

text_DeepL/Scenario_ch_00290_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-6516476001870603031.txt
text_DeepL/Scenario_ch_00340_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3788823659731564397.txt
text_DeepL/Scenario_ch_00450_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5424244914387418467.txt
text_DeepL/Scenario_ch_00680_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--8143999520158681186.txt
text_DeepL/Scenario_ch_00780_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-2342269648680410133.txt

- Scenario 00290 (Wyler), also includes 00300 (Marin)
- Scenario 00340 (Kerrin)
- Scenario 00450 (Frida)
- Scenario 00680 (Falward)
- Scenario 00780 (Gieran)

Batch Upload of recruitment Scenario Files, Day 10 & 11

---

text_DeepL/Main_Battle_Gimmick_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--1701475196546212094.txt

This is the vore plant launcher thing in the Greatwood East.

Update Main_Battle_Gimmick_01 - Line [107] to [112]

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

- Progressed from line [222] to [314]
- Revised line [128], Leene's catchphrase, after getting more context

Update MainScenario_03_en Edit Progression and Revision

---

text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt

Line [42] of MS04 appears during Chapter 3, unvoiced, when you talk to the Elder tree in the Dendriarch's room after Nowa and Marisa decide to join forces to explore the Proving Grounds.

Update MainScenario_04 Editing A Line that Appears Early

---

text_DeepL/MgCardVoice_ch_00010_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5092950374204545572.txt
text_DeepL/MgCardVoice_ch_00640_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--668109487627125933.txt
text_DeepL/Scenario_ch_00310_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2211634552676777395.txt
text_DeepL/Scenario_ch_00320_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-8604356052117801945.txt
text_DeepL/Scenario_ch_00640_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3852503038640627806.txt
text_DeepL/Scenario_ch_00870_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-283392588566847346.txt

Batch uploading a bunch of recruitment scenarios and the first MGCardVoices
Will leave the other MGCardVoices for later

New Scenarios and MGCardVoice - TL'd and Edited

---

text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt

- Edit Started
- Progressed from [0] to [39]

Update MainScenario_04_en Edit Start and Progress

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

- Fixed line [247]
- Edit progress until end of file.
- MS03 First Edit Pass completed

Update MainScenario_03_en Edit Progress, Fixes, and End

---

text_DeepL/HeroTalk_ch_00940_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--134124956078721526.txt

- Edit progress from [51] to [53] & [129]

Update HeroTalk_ch_00940_en Edit Progress

---

text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt

- Edit progress from line [51] to [53] & [129]

Update HeroTalk_ch_00750_en Edit Progress

---

text_DeepL/HeroTalk_ch_00680_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3326662153647456227.txt

- Edit started
- Progressed from [0] to [53] & include [129]

Update HeroTalk_ch_00680_en Edit Started and Progressed

---

text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt

- Edited lines [51] to [53] & [129]

Update HeroTalk_ch_00610_en Edit Progress

---

text_DeepL/HeroTalk_ch_00300_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7949039865492490196.txt

- Progressed line [50] to [53]

Update HeroTalk_ch_00300_en Edit Progress

---

text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt

- Progressed line [51] to [53] & [129]

Update HeroTalk_ch_00220_en Edit Progress

---

text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt

- Progressed line [50] to [53]

Update HeroTalk_ch_00110 Edit Progress

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt

- Fixed Lines [49] to [52]
- Edited Lines [53] to [129]

Update HeroTalk_ch_00010 Edit Progress and Fixes

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt
text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt
text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt
text_DeepL/HeroTalk_ch_00300_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7949039865492490196.txt
text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt
text_DeepL/HeroTalk_ch_00680_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3326662153647456227.txt
text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt
text_DeepL/HeroTalk_ch_00940_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--134124956078721526.txt
text_DeepL/Scenario_ch_00500_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--8763640898368570386.txt
text_DeepL/Scenario_ch_01120_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6644507350931782335.txt

Updates to Herotalks 00010, 00110, 00220, 00300, 00610, 00680, 00750, 00940
DeepL'd and edited recruitment Scenario 00500, and 01120

Batch Pull Req of Misc Day 14 Progress

---

text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt

Progressed mod from line [40] to line [53]

Update MainScenario_04_en Edit Progression

---

text_DeepL/MainScenario_03_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6271230106461225510.txt

Line [312], fixed mistranslated Graybeard to Graybranch.

Update MainScenario_03_en Minor Fix

---

text_DeepL/Scenario_ch_00430_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--2398306009589738620.txt
text_DeepL/Scenario_ch_00560_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--5745748373660101362.txt
text_DeepL/Scenario_ch_00580_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-2097224064325902370.txt

Scenario 00580 (Lam) - Recruitment, Fully DeepL'd and Edited
Scenario 00430 (Nell) - Recruitment, Fully DeepL'd and Edited
Scenario 00560 (Faye & B'baba) - Shared Recruitment, Fully DeepL'd and Edited

Batch upload - Day 17, 18, 19 Recruitment Scenario

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt
text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt
text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt
text_DeepL/HeroTalk_ch_00300_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7949039865492490196.txt
text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt
text_DeepL/HeroTalk_ch_00680_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3326662153647456227.txt
text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt
text_DeepL/HeroTalk_ch_00940_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--134124956078721526.txt
text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt
text_DeepL/Scenario_ch_00240_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5369385244904700634.txt
text_DeepL/Scenario_ch_00610_01_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-1403403604931782588.txt

Uploaded everything from Days 20, 21, and 22.

Bulk upload of Days 20, 21, 22

---

HeroTalk_ch_00010_Repurposed_Contextual_Devnotes.txt
text_DeepL/HeroTalk_ch_00110_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7479258441864237949.txt
text_DeepL/HeroTalk_ch_00220_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-5495501383352162244.txt
text_DeepL/HeroTalk_ch_00300_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--7949039865492490196.txt
text_DeepL/HeroTalk_ch_00610_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7549117700514511410.txt
text_DeepL/HeroTalk_ch_00680_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-3326662153647456227.txt
text_DeepL/HeroTalk_ch_00750_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--3717143291466301070.txt
text_DeepL/HeroTalk_ch_00940_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--134124956078721526.txt
text_DeepL/MainScenario_04_en-CAB-a510f8427b6f727aa2cf8403abe0eca8-7256707865771103466.txt
text_DeepL/MainScenario_05_en-CAB-a510f8427b6f727aa2cf8403abe0eca8--6787315574313703913.txt

Cumulative update Days 25, 26, 27, 28
